export const skills = [
    "Semantic & accessible HTML",
    "React Router",
    "Promises, Async/Await",
    "Responsive Web Design",
    "Redux-Saga",
    "GitHub Pull Request & Review",
    "Teamwork",
    "Redux (Toolkit)",
    "Trello",
    "Markdown", 
    "React Hooks",
    "Scrum",
    "Immutability",
    "Error handling",
    "NPM",
    "CSS BEM convention",
    "Working with API (fetch, axios)",
    "React",
    "CSS Flexbox",
    "JavaSrcipt: ES6",
    "Git",
    "CSS Grid",
];

export const nextSkills = [
    "JS classes",
    "React Context",
    "TypeScript",
    "Node.js",
    "Unit testing",
    "Cypress",
    "Java Backend",
];